import Contact from '@/components/contact/Contact'
import Intro from '@/components/intro/Intro'
import Banner from '@/components/layout/Banner'
import CTA from '@/components/layout/CTA'
import Skills from '@/components/skills/Skills'
import Testimonials from '@/components/testimonials/Testimonials'
import Work from '@/components/work/Work'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrapper">
        <Intro />
        <Banner />
        <Skills />
        <CTA />
        <Work />
        <Testimonials />
        <Contact />
      </div>
    </>
  )
}
